# Generated by Django 4.0.4 on 2022-05-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0003_rename_players_game_player_rename_players_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
