# Generated by Django 4.0.4 on 2022-05-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0005_alter_player_options_remove_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date scheduled'),
        ),
        migrations.AlterField(
            model_name='player',
            name='discordId',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='winners',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamers.game', unique=True),
        ),
        migrations.AlterField(
            model_name='winners',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamers.player', unique=True),
        ),
        migrations.AlterField(
            model_name='winners',
            name='position',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
