# Generated by Django 4.0.4 on 2022-05-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0007_alter_winners_game_alter_winners_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winners',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
