# Generated by Django 4.0.4 on 2022-05-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0009_alter_winners_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='winners',
            unique_together={('position', 'game', 'player')},
        ),
    ]
