# Generated by Django 4.0.4 on 2022-05-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0011_alter_winners_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='winners',
            unique_together={('game', 'player')},
        ),
    ]
