# Generated by Django 4.0.4 on 2022-05-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0012_alter_winners_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='winners',
            unique_together={('game', 'position')},
        ),
    ]
