# Generated by Django 4.0.4 on 2022-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0013_alter_winners_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='date scheduled'),
        ),
    ]
