# Generated by Django 4.0.4 on 2022-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0014_alter_game_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date scheduled'),
        ),
    ]
